server:
  port: ${SERVER_PORT:8080}
  servlet.context-path: ${SERVLET_CONTEXT_PATH:/}

spring:
  # profiles.include: json-logging
  # datasource:
  #   url: ${DATASOURCE_URL}
  #   username: ${DATASOURCE_USERNAME}
  #   password: ${DATASOURCE_PASSWORD}
  jpa:
    open-in-view: false
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources.add-mappings: false
    locale: vi
    supported-locales: vi,en

springdoc:
  api-docs:
    enabled: ${API_DOCS_ENABLED:false}
    path: /docs
  swagger-ui:
    path: /swagger-ui
    operations-sorter: alpha
    tags-sorter: alpha

logging:
  level:
    org:
      hibernate:
        SQL: ${HIBERNATE_SQL_LOG_LEVEL:INFO}
        type.descriptor.sql.BasicBinder: ${HIBERNATE_SQL_BINDER_LOG_LEVEL:INFO}
    com.tth.common.log.RequestResponseBodyLoggerAdvice: ${REQUEST_RESPONSE_BODY_LOG_LEVEL:DEBUG}

auth:
  non-authenticated-paths: ${NON_AUTHENTICATED_PATHS:/actuator/**}
